Voting Polls/polling/polling/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls'))
]

Voting Polls/polling/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name= 'index'),
    path('results/<int:question_id>', views.results, name='results'),
    path('<int:question_id>', views.details, name='details'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

Voting Polls/polling/polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

Voting Polls/polling/polls/views.py
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Question, Choice


# Create your views here.
# to get all the questions
def index(request):
    ques = Question.objects.all()
    return render(request, 'index.html', {'ques': ques})


# to show specific question and choices
def details(request, question_id):
    question = Question.objects.get(pk=question_id)
    return render(request, 'details.html', {'question': question})


# Get question and display result
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    # questi = Question.objects.get(pk=question_id)
    # choic = Choice.objects.get(pk=question_id)
    return render(request, 'results.html', {'choice': question})


# Vote for a question choice
def vote(request, question_id):
    # print(request.POST['choice'])
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'details.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

Voting Polls/polling/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <!-- NavBar -->

    <div class="container">
      <div class="row">
        <div class="col-md-6 m-auto">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

Voting Polls/polling/templates/details.html
{% extends 'base.html' %}
{% block content %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'polls:index' %}">Back To Polls</a>
<h1 class="text-center mb-3">{{ question.question_text }}</h1>

{% if error_message %}
<p class="alert alert-danger">
	<strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
		<div class="form-check">
			<input
				type="radio"
				name="choice"
				class="form-check-input"
				id="choice{{ forloop.counter }}"
				value="{{ choice.id }}"
			/>
			<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
		</div>
	{% endfor %}
	<input type="submit" value="Vote Now" class="btn btn-success btn-lg btn-block mt-4" />
</form>
{% endblock %}

Voting Polls/polling/templates/index.html
{% extends 'base.html' %}
{% block content %}
  <h1 class="text-center mb-3">Poll Questions</h1>
    {% for question in ques %}
      <div class="card mb-3">
        <div class="card-body">
          <p class="lead">{{ question.question_text }}</p>
          <a href="{% url 'polls:details' question.id %}" class="btn btn-primary btn-sm">Vote Now</a>
          <a href="{% url 'polls:results' question.id %}" class="btn btn-secondary btn-sm">Results</a>
        </div>
      </div>
    {% endfor %}
{% endblock %}

Voting Polls/polling/templates/results.html
{% extends 'base.html' %}

{% block content %}
<h1 class="mb-5 text-center">{{ choice.question_text }}</h1>

<ul class="list-group mb-5">
	{% for choice in choice.choice_set.all %}
	<li class="list-group-item">
		{{ choice.choice_text }}  <span class="badge badge-success float-right">{{ choice.votes }} vote{{ choice.votes | pluralize }}</span>
	</li>
	{% endfor %}
</ul>

<a class="btn btn-secondary" href="{% url 'polls:index' %}">Back To Polls</a>
<a class="btn btn-dark" href="{% url 'polls:details' choice.id %}">Vote again?</a>
{% endblock %}